name = "cowsay"
version = "3.8.4"

description = "Talking cow"
homepage = "https://github.com/cowsay-org/cowsay"
license = "GPL-3.0"

[source]
url = "https://github.com/cowsay-org/cowsay/archive/refs/tags/v3.8.4.tar.gz"
sha256 = "c15bc10712835d3a9bcda780dc9453362567bf48d1185905dc7ef2334d79aadd"

[build]
system = "make"

[dependencies]
build = []
runtime = []
