name = "tree"
version = "2.2.1"

description = "Display directories as trees"
homepage = "https://oldmanprogrammer.net/source.php?dir=tree"
license = "GPL-2.0"

[source]
url = "https://oldmanprogrammer.net/tar/tree-2.2.1.tgz"
sha256 = "c4b07931b3fc37bc80d56a367783e7fa7c04ced4befec7f57ed079c38c960400"

[build]
system = "make"

[dependencies]
build = []
runtime = []
