name = "ascii"
version = "3.18"

description = "ASCII table utility"
homepage = "https://github.com/howerj/ascii"
license = "MIT"

[source]
url = "https://github.com/howerj/ascii/archive/refs/tags/3.18.tar.gz"
sha256 = ""

[build]
system = "make"

[dependencies]
build = []
runtime = []
